### ISSUE TITLE
LoadConstStringLongIndex

### ISSUE THREAD

**Issue by longldktmm** [2767mr/hermesToJS#1]
LoadConstStringLongIndex  not in source-sink.json
I need option to skip, I can read raw
This project is very interesting
Try your best

hermesToJS-master\dist\decomp.js:424
                throw new Error('Opcode conversion not implemented: ' + node.instr.opcode);
                ^

Error: Opcode conversion not implemented: LoadConstStringLongIndex
    at Decompiler.convertInstruction (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:424:23)
    at Decompiler.convertInstruction (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:358:29)
    at Decompiler.save (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:203:24)
    at Decompiler.convertBlock (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:173:35)
    at Decompiler.convertBlock (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:159:132)
    at Decompiler.convertBlock (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:160:48)
    at Decompiler.convertBlock (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:160:48)
    at Decompiler.convertBlock (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:156:48)
    at Decompiler.decompileFuction (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:92:28)
    at Decompiler.decompile (D:\Tool\hermesToJS-master\hermesToJS-master\dist\decomp.js:52:29)

**Comment by 2767mr** [comment]
Every instruction needs two parts to be decompiled:
* One source-sink definition which defines which registers are written to and which ones are read and
* An entry in `convertInstruction` in `decomp.ts` which defines the equivalent Javascript AST

The error you experienced occures because I currently only define 39 of the 180 instructions. I am planning more over time as I find example JS snippets that produce given instructions.
This is a lot of grunt work and will take some time, any help is welcome.

**Comment by longldktmm** [comment]
https://github.com/facebook/hermes/blob/32e71761f62ec3608c7614100c3053849004aa53/include/hermes/BCGen/HBC/BytecodeList.def
1. About  source-sink.json, I think I can convert DEFINE_OPCODE  that to source-sink.json. What do you think about this?
2. About: decomp.ts, I think I need read more to have ideal

**Comment by 2767mr** [comment]
You can almost generate `source-sink.json` but not quite.
You can:
* Make entries for all opcode
* For all opcodes you can find out the basic types of the operands (register, constant, etc)

You cannot:
* Tell whether it's a source or sink. And that's the purpose of this file.
You can make your life a bit easier if you assume that the first register is always a source and the rest is a sink. However, this does not always apply.

**Comment by zixing131** [comment]
I also have this error : "Error: Opcode conversion not implemented: TryPutById"

**Comment by 2767mr** [comment]
It now no longer crashes but emits throw statements in the output
