### ISSUE TITLE
Can this be used to decompile?

### ISSUE THREAD

**Issue by U29kaXVt** [2767mr/hermesToJS#2]
I tried to decompile a ReactNative bundle compiled by Hermes with this, but I got some errors.
Am I doing something wrong?
```node
started slp
parsed slp
/home/HermesToJs/dist/disasm.js:62
            throw new Error('Invalid string ID');
            ^

Error: Invalid string ID
    at Disassembler.getString (/data/data/com.termux/files/home/fuckHermes/dist/disasm.js:62:19)
    at Disassembler.disassemble (/data/data/com.termux/files/home/fuckHermes/dist/disasm.js:45:55)
    at Decompiler.decompileFuction (/data/data/com.termux/files/home/fuckHermes/dist/decomp.js:61:35)
    at Decompiler.decompile (/data/data/com.termux/files/home/fuckHermes/dist/decomp.js:50:29)
    at Object.<anonymous> (/data/data/com.termux/files/home/fuckHermes/dist/main.js:16:23)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

Node.js v17.9.0
```

**Comment by 2767mr** [comment]
Yes, it can. However it currently only supports bytecode version 84 and not all instructions are fully supported yet.

**Comment by U29kaXVt** [comment]
thanks
