### ISSUE TITLE
Unreachable? Could not resolve environment.

### ISSUE THREAD

**Issue by godhh** [2767mr/hermesToJS#3]
Tested a version 84 of index.android.bundle, reporting the following message. Any ideas on how to solve it? Thanks!

dummy: IdentifierObject {
        pos: -1,
        end: -1,
        flags: 8,
        modifierFlagsCache: 0,
        transformFlags: 0,
        parent: undefined,
        kind: 79,
        originalKeywordKind: undefined,
        escapedText: 'r144780'
}

/Users/xxs/ws/hermesToJS/src/decomp.ts:744
                        throw new Error('Unreachable? Could not resolve environment.');
         ^
Error: Unreachable? Could not resolve environment.
    at Decompiler.createClosure (/Users/xxs/ws/hermesToJS/src/decomp.ts:744:10)
    at Decompiler.convertInstruction (/Users/xxs/ws/hermesToJS/src/decomp.ts:533:42)
    at Decompiler.emit (/Users/xxs/ws/hermesToJS/src/decomp.ts:176:18)
    at Decompiler.convertBlock (/Users/xxs/ws/hermesToJS/src/decomp.ts:106:25)
    at Decompiler.decompileFuction (/Users/xxs/ws/hermesToJS/src/decomp.ts:80:22)
    at Decompiler.createClosure (/Users/xxs/ws/hermesToJS/src/decomp.ts:766:21)
    at Decompiler.convertInstruction (/Users/xxs/ws/hermesToJS/src/decomp.ts:533:42)
    at Decompiler.emit (/Users/xxs/ws/hermesToJS/src/decomp.ts:176:18)
    at Decompiler.convertBlock (/Users/xxs/ws/hermesToJS/src/decomp.ts:106:25)
    at Decompiler.decompileFuction (/Users/xxs/ws/hermesToJS/src/decomp.ts:80:22)

**Comment by 2767mr** [comment]
It's pretty hard to tell what went wrong from the error and stacktrace alone but since there is still a lot left to do in this project I imagine it will fix itself at some point.

**Comment by 2767mr** [comment]
I have reworked the code a lot. If this is still an issue please reopen.
